# Generated by Django 6.0 on 2025-12-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payloads', '0002_workitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workitem',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='priority',
            field=models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=15),
        ),
    ]
